// Detail Movie
export const GETINFO_ADDRESS_REQUEST = "CheckOutReducer/GETINFO_ADDRESS_REQUEST";
export const GETINFO_ADDRESS_SUCCESS = "CheckOutReducer/GETINFO_ADDRESS_SUCCESS";
export const GETINFO_ADDRESS_FAILED = "CheckOutReducer/GETINFO_ADDRESS_FAILED";
export const GETINFO_ADDRESS_CHAIR = "CheckOutReducer/GETINFO_ADDRESS_CHAIR";
export const GETINFO_ADDRESS_PRICE = "CheckOutReducer/GETINFO_ADDRESS_PRICE";
export const GETBOOKMOVIE_REQUEST = "CheckOutReducer/GETBOOKMOVIE_REQUEST";
export const GETBOOKMOVIE_SUCCESS = "CheckOutReducer/GETBOOKMOVIE_SUCCESS";
export const GETBOOKMOVIE_FAILED = "CheckOutReducer/GETBOOKMOVIE_FAILED";
